apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apigee-01-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <TU_REPO>
    targetRevision: main
    path: charts/apigee-operator/etc/crds
  destination:
    server: https://kubernetes.default.svc
    namespace: apigee
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - ServerSideApply=true
      - Replace=true
