apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apigee-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/MathewLove17/apigeePoc.git
    targetRevision: main
    path: POC/clusters/runtime/apigee-hybrid/base
    directory:
      recurse: false
  destination:
    server: https://clusterapigee-dns-1vt88dy8.hcp.westeurope.azmk8s.io:443
    namespace: apigee
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
