apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apigee-01-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/MathewLove17/apigeePoc.git
    targetRevision: main
    path: /../../charts/apigee-operator/etc/crds
  destination:
    name: clusterapigee
    namespace: apigee
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - ServerSideApply=true
      - Replace=true
