apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "1"
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cert-manager/cert-manager
    targetRevision: v1.19.2
    path: deploy/manifests
  destination:
    name: clusterapigee
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
