apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: management-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MathewLove17/apigeePoc.git
    targetRevision: main
    path: POC/clusters/management/argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
