apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-cert
  namespace: demo
spec:
  secretName: demo-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
  - demo.local
